find_package(THREADS REQUIRED), etc
Background:
```
/home/travis/build/headupinclouds/hunter/examples/spdlog/foo.cpp:(.text._ZN6spdlog7details16async_log_helperC2ESt10shared_ptrINS_9formatterEERKSt6vectorIS2_INS_5sinks4sinkEESaIS8_EEmSt8functionIFvRKSsEENS_21async_overflow_policyERKSD_IFvvEERKNSt6chrono8durationIlSt5ratioILl1ELl1000EEEESM_[_ZN6spdlog7details16async_log_helperC2ESt10shared_ptrINS_9formatterEERKSt6vectorIS2_INS_5sinks4sinkEESaIS8_EEmSt8functionIFvRKSsEENS_21async_overflow_policyERKSD_IFvvEERKNSt6chrono8durationIlSt5ratioILl1ELl1000EEEESM_]+0x200): undefined reference to `pthread_create'
```